DISM.exe /online /Disable-Feature /Featurename:Printing-Foundation-LPRPortMonitor /remove 
DISM.exe /online /Disable-Feature /Featurename:Printing-Foundation-LPDPrintService /remove 
DISM.exe /online /Disable-Feature /Featurename:Printing-Foundation-InternetPrinting-Client /remove   
DISM.exe /online /Disable-Feature /Featurename:FaxServicesClientPackage /remove   
DISM.exe /online /Disable-Feature /Featurename:SNMP /remove  
DISM.exe /online /Disable-Feature /Featurename:WMISnmpProvider /remove   
DISM.exe /online /Disable-Feature /Featurename:Windows-Identity-Foundation /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WebServerRole /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WebServer /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-CommonHttpFeatures /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpErrors /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpRedirect /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ApplicationDevelopment /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-NetFxExtensibility /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-NetFxExtensibility45 /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HealthAndDiagnostics /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpLogging /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-LoggingLibraries /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-RequestMonitor /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpTracing /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-Security /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-URLAuthorization /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-RequestFiltering /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-IPSecurity /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-Performance /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpCompressionDynamic /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WebServerManagementTools /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-ManagementScriptingTools /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-IIS6ManagementCompatibility /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-Metabase /remove   
DISM.exe /online /Disable-Feature /Featurename:WAS-WindowsActivationService /remove  
DISM.exe /online /Disable-Feature /Featurename:WAS-ProcessModel /remove   
DISM.exe /online /Disable-Feature /Featurename:WAS-NetFxEnvironment /remove   
DISM.exe /online /Disable-Feature /Featurename:WAS-ConfigurationAPI /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HostableWebCore /remove      
DISM.exe /online /Disable-Feature /Featurename:IIS-StaticContent /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-DefaultDocument /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-DirectoryBrowsing /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WebDAV /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WebSockets /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-ApplicationInit /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ASPNET45 /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-ASP /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-CGI /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ISAPIExtensions /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-ISAPIFilter /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ServerSideIncludes /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-CustomLogging /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-BasicAuthentication /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-HttpCompressionStatic /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ManagementConsole /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-ManagementService /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-WMICompatibility /remove  
DISM.exe /online /Disable-Feature /Featurename:IIS-LegacyScripts /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-LegacySnapIn /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-FTPServer /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-FTPSvc /remove   
DISM.exe /online /Disable-Feature /Featurename:IIS-FTPExtensibility /remove   
DISM.exe /online /Disable-Feature /Featurename:MSMQ-Container /remove  
DISM.exe /online /Disable-Feature /Featurename:MSMQ-Server /remove   
DISM.exe /online /Disable-Feature /Featurename:MSMQ-Triggers /remove  
DISM.exe /online /Disable-Feature /Featurename:MSMQ-ADIntegration /remove   
DISM.exe /online /Disable-Feature /Featurename:MSMQ-HTTP /remove   
DISM.exe /online /Disable-Feature /Featurename:MSMQ-Multicast /remove  
DISM.exe /online /Disable-Feature /Featurename:MSMQ-DCOMProxy /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-Services45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-HTTP-Activation45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-TCP-Activation45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-Pipe-Activation45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-MSMQ-Activation45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-TCP-PortSharing45 /remove   
DISM.exe /online /Disable-Feature /Featurename:WCF-NonHTTP-Activation /remove   
DISM.exe /online /Disable-Feature /Featurename:NetFx4Extended-ASPNET45 /remove   
DISM.exe /online /Disable-Feature /Featurename:Printing-XPSServices-Features /remove   
DISM.exe /online /Disable-Feature /Featurename:RasCMAK /remove   
DISM.exe /online /Disable-Feature /Featurename:RasRip /remove  
DISM.exe /online /Disable-Feature /Featurename:MSRDC-Infrastructure /remove   
DISM.exe /online /Disable-Feature /Featurename:TelnetClient /remove      
DISM.exe /online /Disable-Feature /Featurename:Xps-Foundation-Xps-Viewer /remove   
DISM.exe /online /Disable-Feature /Featurename:TIFFIFilter /remove   
DISM.exe /online /Disable-Feature /Featurename:WorkFolders-Client /remove   
DISM.exe /online /Disable-Feature /Featurename:SMB1Protocol  
DISM.exe /online /Disable-Feature /Featurename:SearchEngine-Client-Package /remove  
DISM.exe /online /Disable-Feature /Featurename:TFTP /remove  
@pause