Get-AppxPackage -name "Microsoft.ZuneMusic" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Music.Preview" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingTravel" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingHealthAndFitness" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingFoodAndDrink" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.People" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingFinance" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.3DBuilder" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsCamera" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Getstarted" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Office.OneNote" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.MicrosoftSolitaireCollection" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.MicrosoftOfficeHub" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Appconnector" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.CommsPhone" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Messaging" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.MicrosoftStickyNotes" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Office.Sway" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.People" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.SkypeApp" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsPhone" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsSoundRecorder" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.ZuneVideo" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsAlarms" | Remove-AppxPackage
Get-AppxPackage -name "microsoft.windowscommunicationsapps" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsSoundRecorder" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsFeedbackHub" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.WindowsAlarms" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.MicrosoftStickyNotes" | Remove-AppxPackage
Get-AppxPackage -name "Facebook.Facebook" | Remove-AppxPackage
Get-AppxPackage -name "4DF9E0F8.Netflix" | Remove-AppxPackage
Get-AppxPackage -name "9E2F88E3.Twitter" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.OneConnect" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Advertising.Xaml" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingNews" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingSports" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.BingWeather" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.Windows.Photos" | Remove-AppxPackage
Get-AppxPackage -name "king.com.CandyCrushSodaSaga" | Remove-AppxPackage
Get-AppxPackage -name "flaregamesGmbH.RoyalRevolt2" | Remove-AppxPackage
Get-AppxPackage -name "Microsoft.MinecraftUWP" | Remove-AppxPackage

